### ISSUE TITLE
[1.4.0] Compilation error in test_limited_api during test

### ISSUE THREAD

**Issue by olebole** [astropy/extension-helpers#128]
I am trying to package version 1.4.0 for Debian. When running the CI tests during the build, I get a number of compilation errors which I do not fully understand, starting with:
```
[…]
x86_64-linux-gnu-gcc -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/builds/python-team/packages/extension-helpers/debian/output/source_dir=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPy_LIMITED_API=0x030A0000 -Inumpy -I/usr/include/python3.13 -c helpers_test_package/unit02.c -o build/temp.linux-x86_64-cpython-313/helpers_test_package/unit02.o
ERROR Backend subprocess exited when trying to invoke build_wheel
----------------------------- Captured stderr call -----------------------------
/usr/lib/python3/dist-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pytest-of-salsaci/pytest-0/test_limited_api_both_cp310_Tr0/test_pkg/helpers_test_package/unit02.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
helpers_test_package/unit02.c: In function ‘__Pyx_PyCode_New’:
helpers_test_package/unit02.c:692:9: error: implicit declaration of function ‘PyUnstable_Code_NewWithPosOnlyArgs’ [-Wimplicit-function-declaration]
  692 |         PyUnstable_Code_NewWithPosOnlyArgs
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
helpers_test_package/unit02.c:690:12: error: assignment to ‘PyCodeObject *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  690 |     result =
      |            ^
helpers_test_package/unit02.c: In function ‘__Pyx_CyOrPyCFunction_GET_SELF’:
helpers_test_package/unit02.c:816:51: error: ‘PyCFunctionObject’ undeclared (first use in this function); did you mean ‘PyCFunction_Check’?
[…]
```
This happens in **test_limited_api** (all three invocations). Full build log [here](https://salsa.debian.org/python-team/packages/extension-helpers/-/jobs/8046018).

* setuptools 78.1.1
* Cython 3.0.11
* gcc 14.3.0
* Python 3.13.7

**Comment by astrofrog** [comment]
I wonder if this test only works with more recent versions of Cython - in which case we might need to add an importorskip directive with the correct min version.

**Comment by da-woods** [comment]
You almost certainly need Cython >=3.1.

Cython 3.0 could compile one or two toy examples with the Limited API. Support in Cython 3.1 is fairly close to complete.

**Comment by da-woods** [comment]
I'm not completely sure but I think:
* you can optionally build Astropy with the Python Limited API. Doing this requires Cython 3.1.
* you can also build Astropy without the Limited API. That probably works fine with Cython 3.0.
* if you aren't building it with the Limited API then you won't care about the test.
* the test should be skipped if a suitable version isn't available.
* (If you do use the Limited API, then it lets you build one package that can serve multiple Python versions - that may or may not be something you care about).

However, you'd be better waiting for a comment from someone from Astropy - I understand the Python Limited API but I've got fairly little idea what Astropy are using it for.

**Comment by olebole** [comment]
OK, that sounds reasonable; I just skipped this test during build. I don't think that anything more is needed, so closing this issue.
